services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"   # Portainer Web UI (HTTP)
      - "9443:9443"   # Portainer Web UI (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock     # Give Portainer access to the Docker socket
      - ./portainer_data:/data                        # Persist Portainer data
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - ./e2e-tests/custom_headers/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portainer

volumes:
  portainer_data:
